export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Eventsday } from "./Eventsday"
export { default as Eventsnight } from "./Eventsnight"
export { default as Tickets } from "./Tickets"
export { default as Partner } from "./Partner"
export { default as Contactus } from "./Contactus"